// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifmewhlgzavvjdqszgal.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmbWV3aGxnemF2dmpkcXN6Z2FsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEyMjc4OTUsImV4cCI6MjA4NjgwMzg5NX0.T4MIWl0cuDKZVG82RFY3E13jizR6e6aoDbl9NrupOPw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});